[phases.setup]
nixPkgs = ["python311", "python311Packages.pip"]

[phases.install]
cmds = [
  "pip install --upgrade pip",
  "pip install -r requirements.txt"
  "pip install --upgrade google.genai",
]

[phases.build]
cmds = [
  "python -c 'from src.database import init_db; init_db()'"
]

[start]
cmd = "gunicorn src.api:app --workers 2 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT --timeout 600"

